### ISSUE TITLE
Try Clang + address sanitizer

### ISSUE THREAD

**Issue by nayuki** [geoffviola/undefined_behavior_study#1]
Good work experimenting with different compilers on how they catch UB errors, and [writing up](https://github.com/geoffviola/undefined_behavior_study/blob/18564ff44fe133066e596548dfd0d682771169fd/README.md) your findings in a table.

I see you used Clang, GCC, MSVC, and ubsan, but no mention of [asan](https://en.wikipedia.org/wiki/AddressSanitizer). Try using `clang -fsanitize=address foo.cpp`, and watch it catch the out-of-bounds memory accesses and detect uninitialized reads! Also, asan is way better than valgrind - more accurate and faster.

**Comment by geoffviola** [comment]
Good suggestion.  I put the results in https://github.com/geoffviola/undefined_behavior_study/blob/master/README.md.

**Comment by nayuki** [comment]
[Nice update](https://github.com/geoffviola/undefined_behavior_study/blob/c8aca7c32fe9b43023eccfaa1f2a4329708057f7/README.md). I have some additional advice:

* ASan isn't designed to catch uninitialized reads. But [MemSan](https://clang.llvm.org/docs/MemorySanitizer.html) can do so (`-fsanitize=memory`).
* You can add UBSan to ASan or MemSan. I think you can't use ASan and MemSan together.
* The debug build of my C/C++ programs usually uses `-fsanitize=undefined,address`
